# Jira AI Settings

# Projects: List of allowed projects (use "all" to allow all projects)
# Examples: BP, PM, PS
projects:
  - all

# Commands: List of allowed commands (use "all" to allow all commands)
# Available commands: me, projects, task-with-details, project-statuses, list-issue-types, run-jql, update-description, add-comment, create-task, get-issue-statistics, about, transition, add-label-to-issue, delete-label-from-issue, list-colleagues, get-person-worklog
commands:
  - me
  - projects
  - task-with-details
  - run-jql
  - list-issue-types
  - project-statuses
