# Jira AI Settings

# Projects: List of allowed projects (use "all" to allow all projects)
# Examples: BP, PM, PS
projects:
  - all
  #- BP
  #- PM
  #- PS
  # Uncomment below to allow all projects
  # - all

# Commands: List of allowed commands (use "all" to allow all commands)
# Available commands: me, projects, task-with-details, project-statuses, list-issue-types, run-jql, update-description, add-comment, create-task, about
commands:
  - me
  # Uncomment below to allow all commands
  # - all
  # - task-with-details
  # - project-statuses
  # - list-issue-types
  # - update-description
  # - add-comment
  # - create-task
